Sys.setenv(FALK_EXTENDED_USER_RIGHTS="[{\"A\":81,\"R\":\"LU\",\"U\":601032},{\"A\":81,\"R\":\"SC\",\"U\":601032},{\"A\":81,\"R\":\"SC\",\"U\":109834},{\"A\":81,\"R\":\"LU\",\"U\":109834}]")
Sys.setenv(MYSQL_DB_DATA="nnrr")
Sys.setlocale(category = "LC_ALL", locale = "nb_NO.UTF-8")
# Sys.setenv(R_RAP_INSTANCE="DEV")
# Sys.setenv(R_RAP_CONFIG_PATH="C:/Users/kth200/repo/nnrr/dev/config")
