services:
  dev:
    image: rapporteket/nnrr-dev:main
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - .:/home/rstudio/nnrr
      - ~/softlinks/mydata:/home/rstudio/mydata
    ports:
      - "8787:8787"
      - "3838:3838"
    dns:
      - 8.8.8.8
    restart: "no"
    environment:
      DISABLE_AUTH: "true"
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
